plugins {
    id 'com.android.application'
}

android {
    namespace 'com.sahil.TzDraft'
    compileSdk 34

    defaultConfig {
        applicationId "com.sahil.TzDraft"
        minSdk 24
        targetSdk 34
        versionCode 11
        versionName "2.1"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    applicationVariants.configureEach { variant ->
        variant.outputs.configureEach {
            outputFileName = "Draft TZ v${variant.versionName}.apk"
        }
    }
}

dependencies {
}
